### ISSUE TITLE
Mutualizing efforts

### ISSUE THREAD

**Issue by krtek4** [excitoon/MultiPassDisarmed#1]
Hey there,

I've just been made aware of your fork (which isn't really one in the GitHub sense). First of all, I want to say you are perfectly authorized to do so given the license I've chosen, and I am happy someone made a version available for Firefox :) Also, I totally get why someone would want to disable Analytics completely.

As a matter of fact, I nearly never looked at the analytics, I first put them here to check for common errors and try to improve the extension, and in the end, I am not using them.

Can I propose to you to make a PR on the original source code to remove all analytics like you did so we can have only one extension ? I think it would be better for the user and us as there won't be two extensions to manage.

I can even give you full rights on the repo if you are willing to help with the maintenance as I don't have much time myself to do it.

What do you think ?

PS: I am a bit less sure about the renaming of regex to regexp, as I prefer the former, but it's not a deal breaker ;)

**Comment by Francewhoa** [comment]
Hi @excitoon and @krtek4 :) Feel really free to join efforts or not. +1 for joining efforts if you're both interested in this.

@krtek4 :) About MultiPass' analytics/Google Analytics (GA). As a user, one of the main benefit of MultiPassDisarmed is that it come across as having a stronger privacy. I understand it is not MultiPass intention to spy on users or invade their privacy. But MultiPass' [analytics](https://en.wikipedia.org/wiki/Software_analytics) is risky to come across as a [spyware](https://en.wikipedia.org/wiki/Spyware). If analytics are needed by some users. I suggest two things:

- By default deactivate MultiPass' analytics. So that users can decide if they want to opt-in or not. Instead of a small print notice in the documentation or configuration.
- During the MultiPass add-on install, somehow prompt the user. Asking if he/she is interested to opt-in analytics or not. Again by default the setting would be deactivated. How about a check box?

**Comment by krtek4** [comment]
Hi @excitoon,

FYI, I disabled Google Analytics in the latest published version (0.8.2 at the time of writting).

There are also one bugfix and a hack for Firefox was removed, so I reiterate the idea of working together so that your users can also benefit from those changes.

I can give you both commit access to my repo and to the extension on the Mozilla Store if you want and I'll gladly list your name as co-author. Let me know what you think :)

Best,

**Comment by krtek4** [comment]
Just to let everyone know that without any news on this issue I decided to publish the new version myself for Firefox : https://addons.mozilla.org/en-US/firefox/addon/multipass/

Guaranteed 100% without any Analytics :)

@excitoon  Let me know what you wanna do, as I said, I can list you as co-author, give you commit access, or whatever :)

Best,

**Comment by excitoon** [comment]
@krtek4 Hi. Actually I have no intention to support this fork as long as you made friends with Firefox. Great to hear this. I do not need to have any access except creating pull requests. I will just make an announcement, that this fork is no longer being updated and a link to the original, and remove addons from stores.

**Comment by krtek4** [comment]
That works for me :) Thanks!

If at any time you want to fix an issue or make any kind of contribution, you are very welcome.

best,
